---
- name: Configure firewalld
  ansible.posix.firewalld:
    service: "{{ item.key }}"
    zone: "{{ item.value.zone }}"
    state: "{{ item.value.state }}"
    immediate: yes
    permanent: yes
  become: yes
  loop: "{{ lookup('dict', etc_firewalld, wantlist=True) }}"
