---
- name: Merge fstab entries
  set_fact:
    etc_fstab_entries: '{{ etc_fstab_entries | combine(etc_fstab_entries_overwrite, recursive=True) }}'
  when:
    - etc_fstab_entries_overwrite | default()

- name: Configure fstab
  ansible.posix.mount:
    src: "{{ item.value.src }}"
    path: "{{ item.value.path }}"
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.opts }}"
    passno: "{{ item.value.passno }}"
    dump: "{{ item.value.dump }}"
    state: present
  become: yes
  loop: "{{ lookup('dict', etc_fstab_entries, wantlist=True) }}"
