---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ etc_hostname }}"
    use: systemd
  become: yes
  when: etc_set_hostname | bool

- name: Merge fstab entries
  set_fact:
    etc_fstab_entries: '{{ etc_fstab_entries | combine(etc_fstab_entries_overwrite, recursive=True) }}'
  when:
    - etc_fstab_entries_overwrite | default()
    - etc_configure_fstab | bool

- name: Configure fstab
  ansible.posix.mount:
    src: "{{ item.value.src }}"
    path: "{{ item.value.path }}"
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.opts }}"
    passno: "{{ item.value.passno }}"
    dump: "{{ item.value.dump }}"
    state: present
  become: yes
  loop: "{{ lookup('dict', etc_fstab_entries, wantlist=True) }}"
  when: etc_configure_fstab | bool

- name: Include users.yml
  ansible.builtin.include: users.yml
  when:  etc_update_users | bool

- name: Include blscfg.yml
  ansible.builtin.include: blscfg.yml
  when: etc_enable_BLSCFG | bool

- name: Include nts.yml
  ansible.builtin.include: nts.yml
  when: etc_enable_NTS | bool

- name: Include firewalld.yml
  ansible.builtin.include: firewalld.yml
  when: etc_configure_firewalld | bool

- name: Include sysctl.yml
  ansible.builtin.include: sysctl.yml
  when: etc_configure_sysctl | bool

- name: Include btrfs.yml
  ansible.builtin.include: btrfs.yml
  when: etc_configure_btrfs | bool
