---
- name: Include remotes.yml
  ansible.builtin.include: remotes.yml
  when: flatpak_configure_remotes | bool

- name: Include flatpaks.yml
  ansible.builtin.include: flatpaks.yml
  when: flatpak_alter_flatpaks | bool

- name: Enable flatpak Automatic Update
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
  with_items:
    - flatpak-automatic.service
    - flatpak-automatic.timer
  notify:
    - Enable flatpak-automatic
  when: flatpak_automatic_updates | bool
