---
- name: Enable flatpak-automatic
  ansible.builtin.systemd:
    name: flatpak-automatic.timer
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Update Flatpaks
  ansible.builtin.command:
    cmd: flatpak update -y
  become: yes
