---
- name: Include dotfiles.yml
  ansible.builtin.include: dotfiles.yml
  when: home_place_dotfiles | bool

- name: Include gnome.yml
  ansible.builtin.include: gnome.yml
  when: home_configure_gnome | bool
