---
etc_set_hostname: true
etc_enable_BLSCFG: true
etc_update_users: true
etc_enable_NTS: true
etc_configure_firewalld: true
etc_configure_sysctl: true

etc_sysctl_params:
  kernel.unprivileged_bpf_disabled:
    value: 1
    state: present