---
etc_hostname: chapek9

etc_fstab_entries:
  root:
    src: UUID=254d6a53-398a-4a53-93d1-c45e61263791
    path: /
    fstype: btrfs
    opts: noatime,subvol=root,compress=zstd:1,x-systemd.device-timeout=0
    passno: 0
    dump: 0
  home:
    src: UUID=254d6a53-398a-4a53-93d1-c45e61263791
    path: /home
    fstype: btrfs
    opts: subvol=home,compress=zstd:1,x-systemd.device-timeout=0
    passno: 0
    dump: 0

rpm_ostree_kargs_overwrite:
  'i915.enable_psr=0':
    state: present

flatpak_flatpaks_overwrite:
  org.gnome.Firmware:
    state: present
    remote: flathub
